version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "
              sudo wget -O - https://nightly.odoo.com/odoo.key | sudo apt-key add -
              sudo echo "deb http://nightly.odoo.com/11.0/nightly/deb/ ./" >> /etc/apt/sources.list
              sudo apt-get update
              sudo apt-get install odoo -y
            " 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
