version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "rm -dfr /opt/odoo/odoo"
            # ssh $SSH_USER@$SSH_HOST "git -C /opt/odoo clone $CIRCLE_REPOSITORY_URL --single-branch -b 12.0 --depth=1 "
            ssh $SSH_USER@$SSH_HOST "sudo apt install odoo -y" 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
