version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "
              sudo apt-get update
              sudo apt-get install odoo -y
            " 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
